#server
server:
  port: 5000

#dataSource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: 201429

#mybatis-plus config
mybatis-plus:
  mapper-locations: classpath*:com/elvira/blog/mapper/**Mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



